set_property PACKAGE_PIN W5 [get_ports CLK]							
set_property IOSTANDARD LVCMOS33 [get_ports CLK]

# CLK
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK]

# Leds
set_property PACKAGE_PIN U16 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN E19 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property PACKAGE_PIN U19 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property PACKAGE_PIN V19 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property PACKAGE_PIN W18 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property PACKAGE_PIN U15 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property PACKAGE_PIN U14 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property PACKAGE_PIN V14 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property PACKAGE_PIN V13 [get_ports {LED[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
set_property PACKAGE_PIN V3 [get_ports {LED[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
set_property PACKAGE_PIN W3 [get_ports {LED[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
set_property PACKAGE_PIN U3 [get_ports {LED[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
set_property PACKAGE_PIN P3 [get_ports {LED[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[12]}]
set_property PACKAGE_PIN N3 [get_ports {LED[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[13]}]
set_property PACKAGE_PIN P1 [get_ports {LED[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[14]}]
set_property PACKAGE_PIN L1 [get_ports {LED[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[15]}]
	
# 4x 7seg Displays
set_property PACKAGE_PIN U2 [get_ports {disp_sel[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {disp_sel[0]}]
set_property PACKAGE_PIN U4 [get_ports {disp_sel[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {disp_sel[1]}]
set_property PACKAGE_PIN V4 [get_ports {disp_sel[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {disp_sel[2]}]
set_property PACKAGE_PIN W4 [get_ports {disp_sel[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {disp_sel[3]}]
	
set_property PACKAGE_PIN W7 [get_ports {disp_out[6]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {disp_out[6]}]
set_property PACKAGE_PIN W6 [get_ports {disp_out[5]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {disp_out[5]}]
set_property PACKAGE_PIN U8 [get_ports {disp_out[4]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {disp_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {disp_out[3]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {disp_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {disp_out[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {disp_out[2]}]
set_property PACKAGE_PIN V5 [get_ports {disp_out[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {disp_out[1]}]
set_property PACKAGE_PIN U7 [get_ports {disp_out[0]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {disp_out[0]}]

# UART
set_property PACKAGE_PIN J2 [get_ports RX]					
	set_property IOSTANDARD LVCMOS33 [get_ports RX]
set_property PACKAGE_PIN G2 [get_ports TX]					
	set_property IOSTANDARD LVCMOS33 [get_ports TX]
set_property PACKAGE_PIN R2 [get_ports RST]					
	set_property IOSTANDARD LVCMOS33 [get_ports RST]

# BUZZER
	
set_property PACKAGE_PIN J1 [get_ports BUZZER]					
	set_property IOSTANDARD LVCMOS33 [get_ports BUZZER]

# i2c
set_property PACKAGE_PIN V17 [get_ports {HEXDEC}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {HEXDEC}]
	
set_property PACKAGE_PIN N17 [get_ports {SDA}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SDA}]
set_property PACKAGE_PIN P18 [get_ports {SCL}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SCL}]
set_property PACKAGE_PIN P17 [get_ports {IRQ}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {IRQ}]
set_property PACKAGE_PIN R18 [get_ports {SS}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SS}]

# PWM (servo)
set_property PACKAGE_PIN C16 [get_ports PWM_o]					
	set_property IOSTANDARD LVCMOS33 [get_ports PWM_o]

# Stepper
set_property PACKAGE_PIN A14 [get_ports {SOUT[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SOUT[0]}]
set_property PACKAGE_PIN A15 [get_ports {SOUT[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SOUT[2]}]
set_property PACKAGE_PIN A16 [get_ports {SOUT[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SOUT[1]}]
set_property PACKAGE_PIN A17 [get_ports {SOUT[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SOUT[3]}]
	
# Motor control
set_property PACKAGE_PIN K17 [get_ports {MOTOR_CTRL[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {MOTOR_CTRL[3]}]
set_property PACKAGE_PIN L17 [get_ports {MOTOR_CTRL[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {MOTOR_CTRL[2]}]
set_property PACKAGE_PIN M18 [get_ports {MOTOR_CTRL[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {MOTOR_CTRL[1]}]
set_property PACKAGE_PIN M19 [get_ports {MOTOR_CTRL[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {MOTOR_CTRL[0]}]
